name: gke-scheduled-autoscaler-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/gke-scheduled-autoscaler-ci.yml'
      - 'gke-scheduled-autoscaler/**'
  pull_request:
    paths:
      - '.github/workflows/gke-scheduled-autoscaler-ci.yml'
      - 'gke-scheduled-autoscaler/**'
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: build gke-scheduled-autoscaler container
        run: |
          cd gke-scheduled-autoscaler
          docker build --tag gke-scheduled-autoscaler .